---
all:
  children:
    nomad_servers:
      hosts:
        server-001:
          ansible_host: 10.25.5.0
        server-002:
          ansible_host: 10.25.5.1
        server-003:
          ansible_host: 10.25.5.2
    nomad_clients:
      hosts:
        serverclient-001:
          ansible_host: 10.25.5.3
        serverclient-002:
          ansible_host: 10.25.5.4
        serverclient-003:
          ansible_host: 10.25.5.5
    nginx:
      hosts:
        nginx:
          ansible_host: 10.25.5.6
  vars:
    ansible_user: local technical user ##"please change this your ssh technical user with sudo permission"
    domain: dum.seclab.ch
