---
all:
  children:
    nomad_servers:
      hosts:
        nomadsrv-001:
          ansible_host: 10.25.5.0
        nomadsrv-002:
          ansible_host: 10.25.5.1
        nomadsrv-003:
          ansible_host: 10.25.5.2
    nomad_clients:
      hosts:
        nomadclt-001:
          ansible_host: 10.25.5.3
        nomadclt-002:
          ansible_host: 10.25.5.4
        nomadclt-003:
          ansible_host: 10.25.5.5
    nginx:
      hosts:
        nginx:
          ansible_host: 10.25.5.6
  vars:
    ansible_user: scsadmin
    domain: dum.seclab.ch
